// Generated by CoffeeScript 1.8.0
var assert, fib;

assert = require("assert");

fib = (function(make_generator) {
  make_generator = function(n) {
    return (function*(s, i) {
      var value, _i;
      for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
        s.push(s[0] + s[1]);
        value = s.shift();
        (yield null);
      }
      return value;
    })([1, 1], 1);
  };
  return function(n) {
    return (function(generator, done) {
      var value, _ref;
      generator = make_generator(n);
      while (!done) {
        _ref = generator.next(), value = _ref.value, done = _ref.done;
      }
      return value;
    })(null, false);
  };
})(null);

assert.equal(fib(6), 8);
